server:
  servlet:
    context-path: /springbootee

spring:
  datasource:
    #连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: ACCP
    #缓存
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.yoona.springboote.entity